"""Detailed software requirements (DSR): the SRS's own requirement text.

**Generated by `scripts/extract_srs_spec.py` from `HRMS_SRS_v2.0.pdf` §5.**
Do not edit by hand — `test_srs_spec_matches_the_srs_pdf` re-extracts the PDF
and fails if this file disagrees with it.

Where `traceability.py` answers *what is the state of this requirement*, this
module answers *what does the SRS actually ask for*, in the SRS's own order.
That order is what the serial numbers are allocated from, so `SR-042` is a
permanent name for one requirement: a commit, a test or a conversation can cite
it and it will still mean the same thing after other requirements close.

Serial numbers are stable for the life of an SRS revision. A revised SRS may
insert a requirement and renumber everything after it; that is recorded in the
UPDATE_LOG of `scripts/update_todo_pdf.py` rather than papered over.
"""

from __future__ import annotations

from typing import NamedTuple


class Requirement(NamedTuple):
    serial: str      # SR-001 .. SR-113, assigned in SRS document order
    id: str          # FR-<MOD>-<NNN> as printed in the SRS
    priority: str    # H | M | L | S | — (the SRS's own Pri column)
    delta: str       # C | R | N (the SRS's own Δ column)
    provenance: str  # where the statement is printed
    statement: str   # the detailed software requirement


REQUIREMENTS: tuple[Requirement, ...] = (
    Requirement('SR-001', 'FR-AUTH-01', 'M', 'C', '§5', 'Login by employee code (case-insensitive, trimmed) and password. Rate limit 10/min per account and per IP, Redis-backed.'),
    Requirement('SR-002', 'FR-AUTH-02', 'M', 'N', '§5', 'On failed login, the response is identical whether the account is unknown, blocked, archived or the password is wrong: 401 {"er- ror":"invalid_credentials"}. No 403 variants that reveal account state.'),
    Requirement('SR-003', 'FR-AUTH-03', 'M', 'N', '§5', '10 consecutive failures within 15 minutes locks the account for 15 minutes and notifies the user by email.'),
    Requirement('SR-004', 'FR-AUTH-04', 'M', 'C', '§5', 'Sessions are server-side (Redis-backed), 8 h idle timeout, 24 h absolute timeout, HttpOnly, SameSite=Lax, Secure outside local dev. Logout invalidates the server-side session immediately.'),
    Requirement('SR-005', 'FR-AUTH-05', 'M', 'R', '§5', 'Logout closes the active user_sessions row: total_hours = (logout − login) / 3600; audited as LOGOUT.'),
    Requirement('SR-006', 'FR-AUTH-06', 'M', 'R', '§5', 'GET / redirects to /dashboard if authenticated, else /login.'),
    Requirement('SR-007', 'FR-AUTH-07', 'M', 'R', '§5', 'GET /dashboard renders the admin or self dashboard by role; unauthenticated requests get 302 (page) or 401 (API, Accept: application/json).'),
    Requirement('SR-008', 'FR-AUTH-08', 'H', 'C', '§5', 'Forgot-password always returns 202 {"message":"If the account exists, a reset link has been sent."} regardless of match, to prevent enumeration. Rate limit 5/min per IP and per email.'),
    Requirement('SR-009', 'FR-AUTH-09', 'H', 'C', '§5', 'Reset tokens: token_urlsafe(32), hashed at rest, 1 h expiry, single use, invalidated on any successful reset for that account.'),
    Requirement('SR-010', 'FR-AUTH-10', 'M', 'C', '§5', 'Password policy: minimum 10 characters, checked against a breached-password list (e.g. Have I Been Pwned k-anonymity API or an offline corpus); no forced complexity rules or expiry, per NIST SP 800-63B. v1.0’s 6-character minimum is a defect (Appendix A-01).'),
    Requirement('SR-011', 'FR-AUTH-11', 'H', 'N', '§5', 'MFA (TOTP) is required for Super Admin, Admin and Finance roles, and optional for others.'),
    Requirement('SR-012', 'FR-AUTH-12', 'M', 'C', '§5', 'CSRF: a csrf_token cookie plus X-CSRF-Token header (double-submit) is enforced on all mutating requests (POST/PUT/PATCH/DELETE) to /api/*. v1.0 issued the token but never checked it (Appendix A-02).'),
    Requirement('SR-013', 'FR-AUTH-13', 'L', 'C', '§5', 'Credential listing (emp_id, name, role, department) is restricted to Super Admin, requires re-authentication within the last 5 minutes, and is fully audited.'),
    Requirement('SR-014', 'FR-AUTH-14', 'H', 'C', '§5', "A scheduled job purges expired reset tokens hourly and auto-closes breaks Active for more than 12 hours (→ Orphaned, duration_minutes = NULL, ended_reason = 'orphan_timeout'). Reason is recorded, not defaulted to zero, so reports can exclude it."),
    Requirement('SR-015', 'FR-USR-01', 'M', 'R', '§5', 'List GET /api/users: pagination (page, per_page, max 200), filters (search, role, status, department, active), sort on an allow-listed column set; server-side only.'),
    Requirement('SR-016', 'FR-USR-02', 'M', 'C', '§5', 'Create POST /api/users: emp_id matches EMP\\d{3,}, name, email (RFC 5322-plausible, case-insensitive unique), role in the role table, department. Default status Active, allow_login = true. Leave balances are seeded from the leave policy for the employee’s grade/location, not a hard-coded 12/10/20. Welcome email carries a 24 h single-use reset token.'),
    Requirement('SR-017', 'FR-USR-03', 'M', 'R', '§5', 'Update GET/PUT /api/users/<id>: field-level allow-list; role changes are audited with old/new value; email change re-verifies uniqueness.'),
    Requirement('SR-018', 'FR-USR-04', 'H', 'C', '§5', 'Block/unblock: POST /api/users/<id>/block|unblock; blocking force-revokes all active sessions for that user (Redis).'),
    Requirement('SR-019', 'FR-USR-05', 'H', 'R', '§5', 'Archive DELETE /api/users/<id> → Archived; self-archive 409. Restore → Active.'),
    Requirement('SR-020', 'FR-USR-06', 'H', 'C', '§5', 'Purge is removed from the product. Replace with anonymisation: POST /api/users/<id>/anonymize (Super Admin, two-person approval, see FR-USR-06a) scrubs direct identifiers (name→“Former Employee #id”, email, phone, address, bank details) but retains audit_log, payroll_items and statutory records for the legal retention period (§11.4). Hard-deleting audit and payroll data (v1.0 FR-USR-06) is prohibited (Appendix A-03).'),
    Requirement('SR-021', 'FR-USR-06a', 'H', 'N', '§5', 'Anonymisation requires a second Super Admin’s approval (maker-checker) before it executes.'),
    Requirement('SR-022', 'FR-USR-07', 'H', 'R', '§5', 'Bulk POST /api/users/bulk {action, emp_ids[]}: self excluded; per-row result reported, partial failure does not fail the batch.'),
    Requirement('SR-023', 'FR-USR-08', 'L', 'R', '§5', 'Meta, CSV export (async job, §CC-09, for exports > 500 rows), sessions history (last 50).'),
    Requirement('SR-024', 'FR-USR-09', 'H', 'C', '§5', 'Permissions GET/PUT /api/users/<id>/permissions: full replace is audited with a diff (added/removed modules), not just “updated”.'),
    Requirement('SR-025', 'FR-USR-10', 'H', 'C', '§5', 'Bulk import POST /api/users/import: CSV via pandas, processed as a background job with a progress endpoint (GET /api/imports/<job_id>); per-row validation; report {imported, skipped, errors[:50], job_id}.'),
    Requirement('SR-026', 'FR-USR-11', 'M', 'C', '§5', 'Dependents: self CRUD, ownership enforced (emp_id = session.emp_id), not the payload.'),
    Requirement('SR-027', 'FR-USR-12', 'L', 'C', '§5', 'Employee-submitted documents route through the same validation as FR-DOC-02 (MIME sniff, size, malware scan).'),
    Requirement('SR-028', 'FR-USR-13', 'M', 'C', '§5', 'Profile GET/PUT /api/profile: self-edit fields are a strict subset of admin-edit fields (e.g. an employee cannot change their own role, department, manager_emp_id, or salary-linked fields).'),
    Requirement('SR-029', 'FR-USR-14', 'M', 'R', '§5', 'Change password requires the current password and re-authenticates the session token.'),
    Requirement('SR-030', 'FR-USR-15', 'M', 'C', '§5', 'Navigation is rendered from the same policy function as API authorization (CC-11) — one source of truth, not a separate hand-maintained nav rule set.'),
    Requirement('SR-031', 'FR-ATT-01', 'M', 'C', '§5', 'Break types are configurable per organisation/location (seed: Tea 15 min, Lunch 60 min, Personal 30 min); Lunch.requires_approval = true by default and is configurable.'),
    Requirement('SR-032', 'FR-ATT-02', 'M', 'C', '§5', "Start break POST /api/breaks/start {break_type}, idempotency key required: 403 if allow_breaks = false; daily quota checked against Completed breaks since shift_start(employee, today); if requires_approval, an Approved (not Pending) approval for today’s shift date must exist, else 403; any existing Active break is auto-ended (Completed, ended_reason='auto_end_new_break') before the insert; the whole operation is one transaction with a partial unique index preventing two Active rows for one employee (CC-05)."),
    Requirement('SR-033', 'FR-ATT-03', 'M', 'R', '§5', 'End break POST /api/breaks/<id>/end: ownership enforced by employee id, not just findability; duration_minutes = (end − start)/60; audited.'),
    Requirement('SR-034', 'FR-ATT-04', 'M', 'R', '§5', 'List own breaks, scoped to the current shift window.'),
    Requirement('SR-035', 'FR-ATT-05', 'H', 'C', '§5', 'Break approval request POST /api/break-approvals {break_type}: Lunch only; one Pending per employee per shift date enforced by a unique partial index, not just an app check.'),
    Requirement('SR-036', 'FR-ATT-06', 'H', 'C', '§5', 'Approve/reject: allowed if actor is the employee’s manager (including an active delegate, FR-LEA-08a) or has role HR/Admin; conditional update (CC-04); audited; notifies employee.'),
    Requirement('SR-037', 'FR-ATT-07', 'L', 'R', '§5', 'Break-type summary per type: minutes used since shift start, whether approval is required, latest approval status for the shift date.'),
    Requirement('SR-038', 'FR-ATT-08', 'M', 'R', '§5', 'Login-hours query for a given shift date.'),
    Requirement('SR-039', 'FR-ATT-09', 'H', 'C', '§5', 'Shift summary: shift_hours = last_logout − first_login (not sum of sessions) when both exist, else now − first_login for an open shift, capped at the scheduled shift length +25% to avoid a forgotten-logout skewing the figure — flagged estimated: true in that case. productive_hours = shift_hours − break_minutes/60; efficiency = productive_hours / shift_hours × 100.'),
    Requirement('SR-040', 'FR-ATT-10', '—', '—', '§5', '(retired — folded into FR-ATT-09; see Appendix A)'),
    Requirement('SR-041', 'FR-ATT-11', 'H', 'C', '§5', 'Monthly calendar: sessions, breaks, leaves (day-expanded), holidays, and now computed daily status (FR-JOB-01) for each day.'),
    Requirement('SR-042', 'FR-ATT-12', 'L', 'R', '§5', 'Live monitoring (admin): employees currently on an Active break.'),
    Requirement('SR-043', 'FR-ATT-13', 'L', 'R', '§5', 'Break summary (admin): per-employee active/completed counts and total minutes for the current shift window.'),
    Requirement('SR-044', 'FR-ATT-14', 'L', 'R', '§5', 'Recently disposed breaks (admin), last hour.'),
    Requirement('SR-045', 'FR-ATT-15', 'M', 'C', '§5', 'Dashboard stats are computed by a cached query (Redis, 15 s TTL) refreshed by a worker, not recomputed per request; JSON keys are stable (total, logged_in_today, on_break, blocked, pending_leaves).'),
    Requirement('SR-046', 'FR-ATT-16', 'H', 'R', '§5', 'Admin break console: active/disposed/summary in one call; admin dispose ends any Active break with an audited reason.'),
    Requirement('SR-047', 'FR-ATT-17', 'M', 'C', '§5', 'Shift configuration (shift_start, shift_end, Fixed/24x7, weekly-off pattern) is effective-dated (shift_assignments table), not a bare column on users, so a shift change does not rewrite history.'),
    Requirement('SR-048', 'FR-REG-01', 'M', 'R', '§5', 'List with pending_my_approval, status,month filters; manager view includes delegated reports (FR-LEA-08a).'),
    Requirement('SR-049', 'FR-REG-02', 'M', 'C', '§5', 'Create {date, reason, requested_login_time?, requested_logout_time?}: future dates rejected; a specific corrected time is required, not just a text reason, so approval has something concrete to apply (Appendix A-04); one Pending per employee per date, enforced by a unique partial index.'),
    Requirement('SR-050', 'FR-REG-03', 'H', 'C', '§5', 'Approve shall write the corrected time(s) into the day’s session/attendance record and trigger FR-JOB-01 to recompute that day’s status. v1.0 approval only flipped a status flag and never touched attendance data (Appendix A-05). Reject leaves attendance untouched. Cancel: Pending only, by owner or admin.'),
    Requirement('SR-051', 'FR-REG-04', 'M', 'R', '§5', 'Export to Excel (async for large ranges); page shows admin/manager context.'),
    Requirement('SR-052', 'FR-LEA-01', 'M', 'C', '§5', 'List with pending_my_approval / admin filters / self filters, as v1.0, plus delegated-manager visibility.'),
    Requirement('SR-053', 'FR-LEA-02', 'M', 'C', '§5', 'Create {leave_type, start_date, end_date, session (Full/First- half/Second-half), reason}: dates parsed and swapped if reversed; days requested = working days in range per the employee’s weekly-off pattern, minus organisation holidays in range (the same function used at approval and reporting — see FR-LEA-09); balance check is remaining >= requested inside the same transaction as the insert (CC-06); overlap check against Pending/Approved leaves is a database exclusion constraint (CC-05), not just an app query; on success, leave_balance.reserved += requested and the row is inserted Pending.'),
    Requirement('SR-054', 'FR-LEA-03', 'M', 'R', '§5', 'Export to Excel (async for large ranges).'),
    Requirement('SR-055', 'FR-LEA-04', 'H', 'C', '§5', 'Approve: actor is manager (or delegate) or HR/Admin, not the applicant; conditional update Pending→Approved; leave_balance.used_days += days, leave_balance.reserved −= days, in one transaction.'),
    Requirement('SR-056', 'FR-LEA-05', 'H', 'C', '§5', 'Reject: conditional update; leave_balance.reserved −= days. Cancel: Pending only, or Approved with a future start date (with the same reserved/used reversal), by owner or admin.'),
    Requirement('SR-057', 'FR-LEA-06', 'M', 'C', '§5', 'Balance query returns {total, used, reserved, remaining} per type per year; remaining = total − used − reserved.'),
    Requirement('SR-058', 'FR-LEA-07', 'H', 'R', '§5', 'Grants: HR/Admin can add days to one or more employees’ balances for a type/month/year; fully audited as LEAVE_GRANT with before/after totals.'),
    Requirement('SR-059', 'FR-LEA-08', 'M', 'N', '§5', 'Leave policy (accrual rate, carry-forward cap, encashment rule, weekly-off pattern) is configuration per grade/location, versioned by effective date — not a hard-coded 12/10/20 in the seed data.'),
    Requirement('SR-060', 'FR-LEA-08a', 'S', 'N', '§5', 'Approval delegation. A manager can delegate approval authority to another employee for a date range (e.g. while on leave). Delegates appear in pending_my_approval views and their approvals are audited as “approved by delegate for manager X”.'),
    Requirement('SR-061', 'FR-LEA-09', 'M', 'N', '§5', 'The working-day / holiday-deduction function used to compute leave days (FR-LEA-02), the payroll LOP calculation (FR-PAY-04), and the reports “working days” figure (FR-RPT) is the same function, called from one place. v1.0 used three different day-counting rules across these three areas (Appendix A-06).'),
    Requirement('SR-062', 'FR-PAY-01', 'M', 'C', '§5', 'Pages/APIs for salary structures, payroll rates, payroll runs — Finance and Admin roles; HR has read access.'),
    Requirement('SR-063', 'FR-PAY-02', 'M', 'C', '§5', 'Salary structure: {emp_id, basic, hra, allowances[], deductions[], effective_from}; multiple structures per employee are allowed with non-overlapping effective ranges (exclusion constraint). Preview endpoint uses the exact same calculation function as the payroll run (FR-PAY-05) — one function, not two (Appendix A-07).'),
    Requirement('SR-064', 'FR-PAY-03', 'M', 'C', '§5', 'Payroll rates (PF/ESI/PT/TDS) are versioned, effective-dated configuration, editable by Finance, fully audited; a run always uses the rates effective on the run’s period end date.'),
    Requirement('SR-065', 'FR-PAY-04', 'M', 'C', '§5', 'Calculation: gross = basic + hra + Σallowances; pf = min(gross × pf_rate, pf_max); esi = gross × esi_rate if gross ≤ esi_max else 0; pt = pt_amount if gross > pt_threshold else 0; TDS per the configured slab table (not hard-coded percentages); LOP is deducted using FR-LEA-09’s working-day function against the days marked Absent/Half-day by FR-JOB-01; approved, unpaid reimbursements for the period are added to net pay. net = gross − (Σdeductions + pf + esi + pt + tds) − lop_amount + reimbursements. All amounts NUMERIC(14,2).'),
    Requirement('SR-066', 'FR-PAY-05', 'M', 'C', '§5', "Run POST /api/payroll-runs {month, year}: duplicate (month, year, status != 'Cancelled') prevented by a unique constraint; executes as a background job covering every employee with status Active or Onboarding whose salary structure is effective for the period (v1.0 covered only role = Employee, silently excluding managers and HR — Appendix A-08); created in status Draft; progress is pollable."),
    Requirement('SR-067', 'FR-PAY-06', 'H', 'N', '§5', 'Maker-checker approval. Draft → Submitted (Finance) → Approved (a different Finance/Admin user) → Finalized. A run cannot be approved by the user who submitted it. Once Finalized, payroll items are immutable; corrections require a new run (an adjustment run) referencing the original. v1.0 had no approval step (Appendix A-09).'),
    Requirement('SR-068', 'FR-PAY-07', 'H', 'C', '§5', 'Payslip (JSON and PDF), self or admin/Finance; payslip_generated flag set on first PDF generation; PDF stored in object storage, served via presigned URL.'),
    Requirement('SR-069', 'FR-PAY-08', 'H', 'C', '§5', 'Bank file (CSV: employee id, name, net salary, account, IFSC) and TDS report, Finance/Admin only, only for Finalized runs.'),
    Requirement('SR-070', 'FR-PAY-09', 'S', 'R', '§5', 'Review-cycle progress query, and a quarterly scheduled job (FR-JOB) opens the next review cycle.'),
    Requirement('SR-071', 'FR-EXP-01', 'M', 'R', '§5', 'Categories are configurable (seed: 6 as v1.0).'),
    Requirement('SR-072', 'FR-EXP-02', 'M', 'C', '§5', 'Create {cat_id, amount, description, receipt}: emp_id is always taken from the session (CC-10); v1.0 accepted an emp_id override in the request body, allowing a claim to be filed as someone else (Appendix A-10); category existence validated. Inserted Pending.'),
    Requirement('SR-073', 'FR-EXP-03', 'M', 'C', '§5', 'Status transitions are a strict state machine: Pending → Approved/Rejected by manager or HR (self-approval blocked: actor ≠ claim owner); Approved → Paid by Finance only (not “any logged-in user” as in v1.0 — Appendix A-11); each transition is a conditional update and audited.'),
    Requirement('SR-074', 'FR-TKT-01', 'M', 'C', '§5', 'Queues (HR, IT), department-scoped subcategories, SLA target per priority (configurable).'),
    Requirement('SR-075', 'FR-TKT-02', 'M', 'R', '§5', 'Create/list with the same visibility rule as v1.0 (owner, assignee, matching department, or admin); notifies the department and Super Admin.'),
    Requirement('SR-076', 'FR-TKT-03', 'M', 'C', '§5', 'Detail view enforces the same visibility rule server-side, not just in the list query (defence in depth). Comments append with updated_at bump.'),
    Requirement('SR-077', 'FR-TKT-04', 'M', 'C', '§5', 'Status transitions Open → In Progress → Resolved → Closed, and Reopened (new) if a closed ticket receives a comment from the reporter within 7 days. Assignment audited.'),
    Requirement('SR-078', 'FR-DOC-01', 'M', 'R', '§5', 'List scoped to owner unless HR/Admin.'),
    Requirement('SR-079', 'FR-DOC-02', 'M', 'C', '§5', 'Upload: multipart; MIME type is sniffed from content (not trusted from the filename extension), size cap per category, and the file is scanned for malware before being persisted to object storage under a random key. v1.0 validated only extension and size (Appendix A-12).'),
    Requirement('SR-080', 'FR-DOC-03', 'M', 'C', '§5', 'Download: owner or HR/Admin, via presigned URL, audited. Delete: owner or Admin only (v1.0 allowed any authenticated user — Appendix A-13).'),
    Requirement('SR-081', 'FR-ONB-01', 'M', 'C', '§5', 'Five steps: Offer Acceptance & Pre-boarding → Document Collection & Verification → System & Access Provisioning → Workstation & ID Card → Orientation & Buddy Assignment. A pre-hire record can view/upload documents via a scoped pre-boarding token link without a normal login, because allow_login = false until step 3. v1.0 required the same pre-hire user to log in to upload documents while login was disabled — a contradiction (Appendix A-14).'),
    Requirement('SR-082', 'FR-ONB-02', 'M', 'C', '§5', 'Onboarding page/API for HR/Admin with full visibility; candidate/new-hire view is token-scoped.'),
    Requirement('SR-083', 'FR-ONB-03', 'M', 'C', '§5', 'Checklist creation is automatic on offer acceptance (event-driven from FR-ATS-04), not a manual HR API call that can be skipped or duplicated; a unique constraint prevents two active checklists per employee.'),
    Requirement('SR-084', 'FR-ONB-04', 'M', 'C', '§5', 'Document upload/review as v1.0 (size gates, Approve/Reject with mandatory notes on reject), through the FR-DOC-02 validation pipeline.'),
    Requirement('SR-085', 'FR-ONB-05', 'M', 'C', '§5', 'Step advancement is guard-based, automatic once its guard is satisfied, and HR is only asked to confirm physical/logistics steps (workstation ready, ID card issued) — the system does not ask the new hire to “complete their own introduction” as the terminal action (v1.0’s step 5 — Appendix A-15). Step 5 (orientation) is marked complete by the assigned buddy or manager.'),
    Requirement('SR-086', 'FR-ONB-06', 'M', 'R', '§5', 'Status query: own workflow, or (HR/Admin) the list of everyone currently onboarding, with days-in-step.'),
    Requirement('SR-087', 'FR-OFF-01', 'M', 'C', '§5', 'Triggered by a resignation record {emp_id, notice_date, last_working_day, reason, initiated_by} — resignation is a first-class object, not implied. Five stages: Resignation & Acceptance → Knowledge Transfer & Manager Clearance → Asset Return & IT Clearance → Full & Final Settlement → Exit Interview & Access Revocation. Stages 2 and 3 run in parallel, not sequentially (Appendix A-16), both gating stage 4.'),
    Requirement('SR-088', 'FR-OFF-02', 'M', 'R', '§5', 'Tasks per stage, assignable to specific owners (manager, IT, Finance); exit interview scheduling.'),
    Requirement('SR-089', 'FR-OFF-03', 'M', 'C', '§5', 'Stage completion is a conditional update per stage with its own guard (assets returned = 0 outstanding; settlement approved by Finance); access revocation (allow_login = false, sessions killed, permissions cleared) executes automatically at 00:00 IST on the last working day, not only when someone manually finishes stage 5 (Appendix A-17). users.status → Inactive.'),
    Requirement('SR-090', 'FR-PERF-01', 'M', 'C', '§5', 'Goals CRUD, rating 1–5 by manager (not self), transition to Completed.'),
    Requirement('SR-091', 'FR-PERF-02', 'M', 'C', '§5', 'Review cycle create/list restricted to HR/Admin; submit requires the reviewer to be the assigned reviewer for that review (v1.0 allowed any authenticated user to submit any review — Appendix A-18). 360° feedback: reviewer cannot be the subject.'),
    Requirement('SR-092', 'FR-HOL-01', 'M', 'R', '§5', 'National/Optional types, per-location applicability; list with search/filter.'),
    Requirement('SR-093', 'FR-HOL-02', 'M', 'R', '§5', 'CRUD (HR/Admin, holidays permission), duplicate (name, date) per location prevented by a unique constraint; copy year-to-year with Feb-29 handling; import/export; iCal feed.'),
    Requirement('SR-094', 'FR-HOL-03', 'M', 'R', '§5', 'Opt-in/opt-out for Optional holidays, one active opt-in per employee per holiday (unique constraint); approval queue for HR.'),
    Requirement('SR-095', 'FR-ATS-01', 'M', 'C', '§5', 'Stages: Applied → Screened → Interviewed → Offered → Hired, with Rejected/Withdrawn reachable from any stage before Hired. Pipeline view aggregates counts per job per stage.'),
    Requirement('SR-096', 'FR-ATS-02', 'M', 'C', '§5', 'Jobs and candidates CRUD (HR/Admin); candidate status change via the same stage machine (no arbitrary jump to Hired).'),
    Requirement('SR-097', 'FR-ATS-03', 'M', 'C', '§5', 'Convert-to-employee is not a manual action — it is a consequence of POST /api/offers/<id>/accept (FR-ATS-04). A candidate reaches Hired only through an accepted offer, closing the v1.0 gap where a candidate could be marked Hired directly without ever having an offer (Appendix A-19).'),
    Requirement('SR-098', 'FR-ATS-04', 'M', 'C', '§5', 'Offers: {candidate_id, offered_salary, basic_pct, hra_pct, allowances_pct} where the three percentages sum to 100 (validated) — v1.0’s fixed 50/20/20 split silently discarded 10% of salary (Appendix A-20). Accept → candidate Hired, creates the salary structure and (via a domain event) triggers onboarding checklist creation (FR-ONB-03). Reject/Accept on a missing or already-decided offer returns 404/409, not a silent no-op (v1.0’s idempotent-but-wrong 200 — Appendix A-21).'),
    Requirement('SR-099', 'FR-JOB-01', 'M', 'N', '§5', 'Daily attendance finalisation, nightly per shift date: for every active employee, classify the day as Present, Half-day, Absent, On Leave, Holiday or Weekly-off, from sessions, approved leave, holidays and the employee’s weekly-off pattern (not a hard-coded Mon–Fri — Appendix A-22). Written to attendance_days, the single source for reports and payroll LOP. Idempotent: re-running for a date replaces that date’s rows in one transaction.'),
    Requirement('SR-100', 'FR-JOB-02', 'H', 'R', '§5', 'Hourly: purge expired reset tokens; close orphaned breaks (FR-AUTH-14).'),
    Requirement('SR-101', 'FR-JOB-03', 'S', 'R', '§5', 'Quarterly: open the next performance review cycle (FR-PAY-09).'),
    Requirement('SR-102', 'FR-JOB-04', 'M', 'N', '§5', 'Nightly: revoke access for employees whose last working day was today (FR-OFF-03).'),
    Requirement('SR-103', 'FR-JOB-05', 'M', 'N', '§5', 'The scheduler runs as exactly one active instance (leader election via a Redis or Postgres advisory lock), independent of how many web or worker pods are running. v1.0’s in-process APScheduler duplicated jobs under multiple gunicorn workers (Appendix A-23).'),
    Requirement('SR-104', 'FR-ANL-01', 'M', 'C', '§5', 'Headcount, leave trends, expense summary, performance summary — as v1.0, served from materialized views refreshed on a schedule, with a documented “as of” timestamp on the response.'),
    Requirement('SR-105', 'FR-ANL-02', 'S', 'C', '§5', 'Attrition risk score: the heuristic weights (leave frequency, regularization frequency, early-break frequency, attendance ratio) are configuration, reviewed with HR before go-live, not fixed constants (Appendix A-24), and the endpoint states the score is a heuristic indicator, not a prediction, in its response metadata.'),
    Requirement('SR-106', 'FR-RPT-01', 'M', 'C', '§5', 'Self-service and admin/HR views; self-service is enforced by ignoring any emp_id/department the caller supplies and substituting the caller’s own scope server-side (v1.0 already did this — retained and covered by an explicit test, Appendix A-25 notes it as “verify, not assumed”). “Working days” uses FR-LEA-09’s shared function.'),
    Requirement('SR-107', 'FR-RPT-02', 'M', 'C', '§5', 'Excel export (async for ranges > 1 month or > 200 employees) and department summary.'),
    Requirement('SR-108', 'FR-AUD-01', 'M', 'C', '§5', 'Every mutating action writes an audit row{actor, action, entity, entity_id, before, after, ip, request_id, created_at} via the transactional outbox (CC-09); the audit log is never purged by the application (only by an explicit, documented, legally-driven retention job — see §11.4); audit_log is excluded from FR-USR-06 anonymisation for the retention period, then the actor reference is generalised, not deleted.'),
    Requirement('SR-109', 'FR-NOT-01', 'M', 'C', '§5', 'List (last 50) with unread count; delivered in-app and by email per category preference, via the outbox (CC-09) so a slow SMTP provider cannot block the request that triggered the notification.'),
    Requirement('SR-110', 'FR-NOT-02', 'M', 'C', '§5', '“Mark as read” sets is_read = true and does not delete the row — v1.0’s /read endpoint deleted rows, so read notifications vanished instead of being marked (Appendix A-26). A separate, explicit “clear” action may delete.'),
    Requirement('SR-111', 'FR-NOT-03', 'S', 'R', '§5', 'Preferences per category (Onboarding, Leaves, Expenses, Tickets, Payroll, Tickets-SLA), {in_app, email} each, default true.'),
    Requirement('SR-112', 'FR-AST-01', 'M', 'C', '§5', 'Issue/return, own-assets view, admin/IT list and CRUD; return sets Returned/return_date; outstanding asset count feeds the offboarding gate (FR-OFF-03).'),
    Requirement('SR-113', 'FR-ANL-04', 'S', 'C', 'Appendix A-24 (v1.0 id; v2.0 restates the rule inside FR-ANL-02)', 'Attrition-risk formula weights (0.4, 1.5, 0.8, 3) must be configuration, reviewed with HR before go-live, not fixed constants.'),
)


BY_ID: dict[str, Requirement] = {r.id: r for r in REQUIREMENTS}
ORDER: tuple[str, ...] = tuple(r.id for r in REQUIREMENTS)


def serial(rid: str) -> str:
    """`SR-001`-style serial for a requirement id.

    Raises `KeyError` for an id the SRS does not carry, which is what should
    happen: a requirement the spec does not name has no serial to give it.
    """
    return BY_ID[rid].serial


def statement(rid: str) -> str:
    """The SRS's requirement text for `rid`."""
    return BY_ID[rid].statement

