"""add corrected ATS/onboarding/offboarding workflow structures

Revision ID: 0002_lifecycle_workflows
Revises: 0001_baseline
"""

from alembic import op

revision = "0002_lifecycle_workflows"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # These columns are additive compatibility for databases created from the
    # original baseline; the canonical schema already declares them.
    op.execute(
        "ALTER TABLE onboarding_tasks ADD COLUMN IF NOT EXISTS stage INTEGER NOT NULL DEFAULT 1"
    )
    op.execute(
        "ALTER TABLE onboarding_workflow ADD COLUMN IF NOT EXISTS step_started_at TIMESTAMPTZ NOT NULL DEFAULT now()"
    )
    op.execute(
        "ALTER TABLE offboarding_tasks ADD COLUMN IF NOT EXISTS stage INTEGER NOT NULL DEFAULT 1"
    )
    op.execute(
        "ALTER TABLE exit_interviews ADD COLUMN IF NOT EXISTS offboard_id BIGINT"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS offboarding_approvals (
            approval_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            offboard_id   BIGINT NOT NULL REFERENCES offboarding_workflow(offboard_id),
            actor_emp_id  VARCHAR NOT NULL REFERENCES users(emp_id),
            action        VARCHAR NOT NULL,
            from_status   VARCHAR NOT NULL,
            to_status     VARCHAR NOT NULL,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_active_offer_candidate "
        "ON offer_letters (candidate_id) WHERE status IN ('Pending', 'Accepted')"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_offboarding_workflow_emp "
        "ON offboarding_workflow (emp_id, completed)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_offboarding_approvals_offboard "
        "ON offboarding_approvals (offboard_id)"
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS offboarding_settlements (
            settlement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            offboard_id     BIGINT NOT NULL UNIQUE REFERENCES offboarding_workflow(offboard_id),
            pending_payroll NUMERIC(14,2) NOT NULL DEFAULT 0,
            lop_adjustment  NUMERIC(14,2) NOT NULL DEFAULT 0,
            leave_encashment NUMERIC(14,2) NOT NULL DEFAULT 0,
            deductions      NUMERIC(14,2) NOT NULL DEFAULT 0,
            asset_damage    NUMERIC(14,2) NOT NULL DEFAULT 0,
            total_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
            status          VARCHAR NOT NULL DEFAULT 'Prepared',
            prepared_by     VARCHAR NOT NULL REFERENCES users(emp_id),
            prepared_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
            approved_by     VARCHAR REFERENCES users(emp_id),
            approved_at     TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_offboarding_settlements_offboard "
        "ON offboarding_settlements (offboard_id)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_active_offer_candidate")
    op.execute("DROP TABLE IF EXISTS offboarding_settlements")
    op.execute("DROP TABLE IF EXISTS offboarding_approvals")
    op.execute("DROP INDEX IF EXISTS ix_offboarding_workflow_emp")
    op.execute("ALTER TABLE exit_interviews DROP COLUMN IF EXISTS offboard_id")
    op.execute("ALTER TABLE offboarding_tasks DROP COLUMN IF EXISTS stage")
    op.execute("ALTER TABLE onboarding_tasks DROP COLUMN IF EXISTS stage")
    op.execute("ALTER TABLE onboarding_workflow DROP COLUMN IF EXISTS step_started_at")
