"""background import jobs (FR-USR-04 bulk load)

Revision ID: 0004_import_jobs
Revises: 0003_lifecycle_hardening

The v1.0 CSV user import ran inside the request, so a large file held a worker
open for the whole load and left no record of what happened. The job table makes
the load asynchronous and inspectable: the route validates the header, stores the
upload, records a ``pending`` job and returns ``202``; a dispatcher claims one
job at a time with an atomic status transition and writes the outcome back.

``error_summary`` is JSONB like the other v2.0 audit-shaped tables. The
compatibility schema gets the INTEGER/no-sequence shape from ``init_db`` and
routes through the sequence-safe allocator, exactly like ``outbox_events``.
"""

from alembic import op

revision = "0004_import_jobs"
down_revision = "0003_lifecycle_hardening"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS import_jobs (
            job_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_type        VARCHAR NOT NULL DEFAULT 'users',
            status          VARCHAR NOT NULL DEFAULT 'pending',
            filename        VARCHAR NOT NULL,
            stored_path     VARCHAR,
            total_rows      INTEGER NOT NULL DEFAULT 0,
            processed_rows  INTEGER NOT NULL DEFAULT 0,
            imported        INTEGER NOT NULL DEFAULT 0,
            skipped         INTEGER NOT NULL DEFAULT 0,
            error_summary   JSONB,
            created_by      VARCHAR REFERENCES users(emp_id),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            started_at      TIMESTAMPTZ,
            finished_at     TIMESTAMPTZ,
            failure_reason  VARCHAR
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_import_jobs_status ON import_jobs (status, created_at)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_import_jobs_status")
    op.execute("DROP TABLE IF EXISTS import_jobs")
