"""two-person anonymisation requests (FR-USR)

Revision ID: 0005_anonymisation_requests
Revises: 0004_import_jobs

The request is the two-person control: a requester proposes, a different
approver confirms, and only then does the system apply the erasure. Keeping the
two states in a table (rather than in a UI convention) means the rule survives a
crash, a retry and a second browser.

``plan_summary``/``result_summary`` are JSONB like the other v2.0 audit-shaped
tables. They deliberately hold *no* erased value: the record of the erasure must
not defeat it. The compatibility schema receives the INTEGER/no-sequence shape
from ``init_db``.
"""

from alembic import op

revision = "0005_anonymisation_requests"
down_revision = "0004_import_jobs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS anonymisation_requests (
            request_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emp_id        VARCHAR NOT NULL REFERENCES users(emp_id),
            status        VARCHAR NOT NULL DEFAULT 'proposed',
            requested_by  VARCHAR REFERENCES users(emp_id),
            confirmed_by  VARCHAR REFERENCES users(emp_id),
            plan_summary  JSONB,
            result_summary JSONB,
            failure_reason VARCHAR,
            requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            confirmed_at  TIMESTAMPTZ,
            applied_at    TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_anonymisation_requests_emp "
        "ON anonymisation_requests (emp_id, status)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_anonymisation_requests_emp")
    op.execute("DROP TABLE IF EXISTS anonymisation_requests")
