"""per-category notification preferences (FR-NOT-03)

Revision ID: 0008_notification_preferences
Revises: 0007_holiday_unique_location

The SRS asks for "Preferences per category (Onboarding, Leaves, Expenses,
Tickets, Payroll, Tickets-SLA), {in_app, email} each, default true." The
``category`` column on ``notifications`` was written for it and nothing ever read
it, so this is the missing half: a table of what each employee wants.

**A row is optional, and that is the design.** "Default true" is expressed by the
*absence* of a row, not by a row saying ``true``. Storing one row per employee per
category would mean seven rows created for every employee on first login, a table
to backfill every time a category is added, and a write on a code path that
otherwise has none. A missing row is the default, so adding a category is a no-op
for everyone already in the system.

That also makes the constraint partial in the same way ``uq_holiday_optins_active``
is: the primary key is ``(emp_id, category)``, so there is at most one row per
pair and no backfill can produce two.

``in_app`` and ``email`` are ``BOOLEAN NOT NULL DEFAULT TRUE`` rather than
nullable. A NULL would mean "unset", which is the same thing the missing row
already means, so it would add a second spelling of the default for a reader to
mis-handle.

**This revision adds no constraint on delivery.** The ``email`` column is stored
and reported, and nothing consumes it yet, because the app has no automatic email
delivery path: ``POST /api/send-notification-email`` is a manual admin endpoint
that chooses its own recipient. The traceability matrix records that as the open
half of FR-NOT-03 rather than the requirement being called done.
"""

from alembic import op

revision = "0008_notification_preferences"
down_revision = "0007_holiday_unique_location"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS notification_preferences (
            pref_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emp_id   VARCHAR NOT NULL REFERENCES users(emp_id),
            category VARCHAR NOT NULL,
            in_app   BOOLEAN NOT NULL DEFAULT TRUE,
            email    BOOLEAN NOT NULL DEFAULT TRUE,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_notification_preferences UNIQUE (emp_id, category)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_notification_preferences_emp "
        "ON notification_preferences (emp_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS notification_preferences")
