"""manual leave grants (FR-LEA-07)

Revision ID: 0011_leave_grants
Revises: 0010_leave_days_stored

The SRS asks for "Grants: HR/Admin can add days to one or more employees' balances
for a type/month/year; fully audited as LEAVE_GRANT with before/after totals", at
**High** priority. Nothing implemented it: an administrator could not add a single day
to a balance, and only a policy assignment or the accrual job could change one.

**Why a new table rather than a write to ``leave_balance.total_days``.** That column
is *derived*: ``leave_policy.ensure_balances`` recomputes it from the effective policy
on every read and overwrites it. A manual adjustment written there would therefore be
silently erased the next time anybody opened the balance — an administrator's grant
surviving only until the next page load, with no audit row able to explain where it
went. So a grant is a row, and ``entitlement_days`` adds the year's grants to the
policy's figure. The two halves of that decision live in ``leave_policy.py``.

``grant_month`` is stored because the requirement says "for a type/month/year", but
only the year feeds the entitlement — a balance row is per year, so a grant cannot be
attributed more finely than the thing it adjusts. Keeping the month on the record means
an administrator can later ask "which month did I correct?" and get an answer.

``granted_by`` is a plain ``VARCHAR`` and **nullable**, matching
``monthly_leave_grants`` where it is NULL for a system accrual. Here it is normally an
administrator's ``emp_id``; it is not a foreign key to ``users`` because
``monthly_leave_grants`` already established that pattern for this exact ledger and a
grant may legitimately be recorded by a migration or a script with no employee actor.

**Additive, and no backfill.** A new table has nothing to backfill, and nothing reads
it until this revision is applied — so ``entitlement_days`` finds no rows and every
existing balance resolves exactly as it did before.
"""

from alembic import op

revision = '0011_leave_grants'
down_revision = '0010_leave_days_stored'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS leave_grants (
            grant_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            emp_id         VARCHAR NOT NULL REFERENCES users(emp_id),
            leave_type     VARCHAR NOT NULL,
            days           INTEGER NOT NULL,
            grant_month    INTEGER,
            grant_year     INTEGER NOT NULL,
            granted_by     VARCHAR,
            reason         TEXT,
            created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    # One query per balance read is `SUM(days) WHERE emp_id AND leave_type AND year`,
    # which is every row of the table. Indexed because that is the only access pattern
    # and the table is read on every `/api/leave-balance` call.
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_leave_grants_emp_type_year
            ON leave_grants (emp_id, leave_type, grant_year)
    """)


def downgrade():
    op.execute('DROP TABLE IF EXISTS leave_grants')
