-- ============================================================================
-- HRMS v2.0 — Target PostgreSQL schema (baseline)
-- ============================================================================
-- Source of truth for the Postgres target schema (SRS v2.0 §7, §14 Phase 0-1).
-- This file is split into two parts so it can be used two ways:
--
--   PART A (tables, seed-safe)   — safe to create with dirty legacy data
--   PART B (invariants)          — constraints/indexes activated only after
--                                  the Phase-1 ETL data-cleanup pass runs
--
-- 1. Fresh environment (no data):  run the whole file, or `alembic upgrade head`.
-- 2. Migration environment: the ETL (scripts/migrate_duckdb_to_postgres.py)
--    executes PART A, loads + cleans DuckDB data, then executes PART B.
--
-- Conventions (CC-01..CC-16):
--   * PKs are BIGINT GENERATED BY DEFAULT AS IDENTITY so migrated legacy IDs
--     load directly; a later Phase-3 pass (CC-01) converts to
--     GENERATED ALWAYS and audits gen_id() callers at runtime.
--   * Money is NUMERIC(14,2) (CC-03). Times are TIMESTAMPTZ, UTC (CC-02).
--   * Uniqueness/non-overlap invariants are DB-enforced (CC-05).
-- ============================================================================

BEGIN;

-- Required by the leave-overlap exclusion constraint (CC-05, FR-LEA-02)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ══════════════════════════════════════════════════════════════════════════
--  USERS / IDENTITY / ORG
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE users (
    emp_id                    VARCHAR PRIMARY KEY,
    name                      VARCHAR NOT NULL,
    email                     VARCHAR NOT NULL,
    password                  VARCHAR NOT NULL,
    role                      VARCHAR NOT NULL DEFAULT 'Employee',
    department                VARCHAR,
    designation               VARCHAR,
    manager_emp_id            VARCHAR REFERENCES users(emp_id),
    phone                     VARCHAR,
    date_of_birth             DATE,
    date_of_joining           DATE,
    address                   VARCHAR,          -- PII (pii_reveal)
    emergency_contact_name    VARCHAR,          -- PII
    emergency_contact_phone   VARCHAR,          -- PII
    status                    VARCHAR NOT NULL DEFAULT 'Active',
    allow_login               BOOLEAN NOT NULL DEFAULT TRUE,
    allow_breaks              BOOLEAN NOT NULL DEFAULT TRUE,
    first_login               TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_super_admin            BOOLEAN NOT NULL DEFAULT FALSE,   -- §2.2
    candidate_id              BIGINT                              -- FR-ATS-03: reachable only via accepted offer
);
CREATE INDEX ix_users_role_department ON users (role, department);
-- uq_users_email_ci (FR-USR-02, lower(email) unique) lives in PART B: legacy
-- DuckDB never enforced email uniqueness, so duplicates must be resolved in the
-- Phase-1 cleanup pass before this index can be created.

-- Effective-dated shift configuration (FR-ATT-17). Replaces users.shift_start/shift_end.
CREATE TABLE shift_assignments (
    assignment_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id                VARCHAR NOT NULL REFERENCES users(emp_id),
    shift_type            VARCHAR NOT NULL DEFAULT 'Fixed',       -- Fixed | 24x7
    shift_start           TIME NOT NULL,
    shift_end             TIME NOT NULL,
    weekly_off_pattern    VARCHAR DEFAULT 'Sat,Sun',              -- used by FR-LEA-09 / FR-JOB-01
    effective_from        DATE NOT NULL,
    effective_to          DATE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- no_overlapping_shift (invariant) lives in PART B, alongside the other CC-05 rules.
CREATE INDEX ix_shift_assignments_emp ON shift_assignments (emp_id, effective_from);

-- ══════════════════════════════════════════════════════════════════════════
--  AUTH / SESSION
-- ══════════════════════════════════════════════════════════════════════════
-- Session data live in Redis in v2.0 (instant revocation). This table keeps
-- the per-day login/logout record used by attendance/reports (FR-AUTH-05/ATT-08).

CREATE TABLE user_sessions (
    session_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        VARCHAR NOT NULL REFERENCES users(emp_id),
    login_time    TIMESTAMPTZ NOT NULL,
    logout_time   TIMESTAMPTZ,
    total_hours   NUMERIC(10,2),
    session_date  DATE
);
CREATE INDEX ix_user_sessions_emp_date ON user_sessions (emp_id, session_date);

-- Reset tokens are SHA-256 hashes at rest in v2.0 (FR-AUTH-09). Schema is unchanged.
CREATE TABLE password_reset_tokens (
    token_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    token       VARCHAR NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_reset_tokens_emp ON password_reset_tokens (emp_id);

-- TOTP secrets, encrypted at rest (FR-AUTH-11)
CREATE TABLE mfa_credentials (
    cred_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id           VARCHAR NOT NULL REFERENCES users(emp_id),
    secret_encrypted VARCHAR NOT NULL,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at     TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_mfa_emp ON mfa_credentials (emp_id);

-- ══════════════════════════════════════════════════════════════════════════
--  BREAKS
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE break_types (
    break_type           VARCHAR PRIMARY KEY,
    daily_limit_minutes  INTEGER,
    description          VARCHAR
);

CREATE TABLE break_approvals (
    approval_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    break_type   VARCHAR NOT NULL REFERENCES break_types(break_type),
    break_date   DATE NOT NULL,             -- shift date (CC-02)
    reason       VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Pending',
    approved_by  VARCHAR REFERENCES users(emp_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_break_approvals_emp ON break_approvals (emp_id, break_date);

CREATE TABLE breaks (
    break_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id           VARCHAR NOT NULL REFERENCES users(emp_id),
    break_type       VARCHAR NOT NULL REFERENCES break_types(break_type),
    start_time       TIMESTAMPTZ NOT NULL,
    end_time         TIMESTAMPTZ,
    duration_minutes INTEGER,
    break_date       DATE,
    status           VARCHAR NOT NULL DEFAULT 'Active',  -- Active|Completed|Orphaned
    ended_reason     VARCHAR       -- orphan_timeout|admin_dispose|auto_end_new_break (FR-ATT-02/FR-AUTH-14)
);
CREATE INDEX ix_breaks_emp_date ON breaks (emp_id, break_date);

-- ══════════════════════════════════════════════════════════════════════════
--  LEAVE  (FR-LEA)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE leave_requests (
    leave_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    leave_type   VARCHAR NOT NULL,
    start_date   DATE NOT NULL,
    end_date     DATE NOT NULL,
    year         INTEGER NOT NULL DEFAULT 0,
    "session"    VARCHAR NOT NULL DEFAULT 'Full',   -- Full|First-half|Second-half (FR-LEA-02)
    reason       VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Pending',
    approved_by  VARCHAR REFERENCES users(emp_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    version      INTEGER NOT NULL DEFAULT 1         -- CC-08 optimistic locking
);
CREATE INDEX ix_leave_requests_emp ON leave_requests (emp_id, status);

CREATE TABLE leave_balance (
    balance_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    leave_type  VARCHAR NOT NULL,
    total_days  INTEGER NOT NULL DEFAULT 0,
    used_days   INTEGER NOT NULL DEFAULT 0,
    reserved    INTEGER NOT NULL DEFAULT 0,         -- FR-LEA-06: reserved by Pending leaves
    year        INTEGER NOT NULL
);
CREATE INDEX ix_leave_balance_emp ON leave_balance (emp_id, year);

-- Per-employee leave policy assignment, effective-dated (FR-LEA-08)
CREATE TABLE leave_policy_assignments (
    assignment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id             VARCHAR NOT NULL REFERENCES users(emp_id),
    location           VARCHAR,
    grade              VARCHAR,
    accrual_rate       NUMERIC(6,2),
    carry_forward_cap  INTEGER,
    encashment_rule    VARCHAR,
    weekly_off_pattern VARCHAR,
    effective_from     DATE NOT NULL,
    effective_to       DATE
);
ALTER TABLE leave_policy_assignments ADD CONSTRAINT no_overlapping_policy
    EXCLUDE USING gist (
        emp_id WITH =,
        daterange(effective_from, effective_to, '[)') WITH &&
    );

CREATE TABLE monthly_leave_grants (
    grant_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     VARCHAR NOT NULL REFERENCES users(emp_id),
    leave_type VARCHAR NOT NULL,
    days       INTEGER NOT NULL,
    month      INTEGER NOT NULL,
    year       INTEGER NOT NULL,
    granted_by VARCHAR REFERENCES users(emp_id),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_leave_grants_emp ON monthly_leave_grants (emp_id, year);

-- Manager → delegate approval authority for a date range (FR-LEA-08a)
CREATE TABLE approval_delegations (
    delegation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegator_id  VARCHAR NOT NULL REFERENCES users(emp_id),   -- manager
    delegate_id   VARCHAR NOT NULL REFERENCES users(emp_id),
    starts_on     DATE NOT NULL,
    ends_on       DATE NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE approval_delegations ADD CONSTRAINT no_overlapping_delegation
    EXCLUDE USING gist (
        delegator_id WITH =,
        daterange(starts_on, ends_on, '[]') WITH &&
    );

-- ══════════════════════════════════════════════════════════════════════════
--  REGULARIZATION  (FR-REG)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE regularization_requests (
    request_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id                 VARCHAR NOT NULL REFERENCES users(emp_id),
    request_date           DATE NOT NULL,
    reason                 VARCHAR NOT NULL,
    requested_login_time   TIME,       -- FR-REG-02 (was missing in v1.0, A-04)
    requested_logout_time  TIME,
    status                 VARCHAR NOT NULL DEFAULT 'Pending',
    approved_by            VARCHAR REFERENCES users(emp_id),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ,
    version                INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX ix_regularization_emp ON regularization_requests (emp_id, request_date);

-- Output of the nightly attendance job (FR-JOB-01); single source for reports/payroll LOP.
CREATE TABLE attendance_days (
    attendance_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id          VARCHAR NOT NULL REFERENCES users(emp_id),
    attendance_date DATE NOT NULL,
    status          VARCHAR NOT NULL,   -- Present|Half-day|Absent|On Leave|Holiday|Weekly-off
    shift_hours     NUMERIC(8,2),
    source          VARCHAR NOT NULL DEFAULT 'job',
    version         INTEGER NOT NULL DEFAULT 1,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE attendance_days ADD CONSTRAINT uq_attendance_emp_date UNIQUE (emp_id, attendance_date);
CREATE INDEX ix_attendance_days_emp ON attendance_days (emp_id, attendance_date);

-- ══════════════════════════════════════════════════════════════════════════
--  HOLIDAYS  (FR-HOL)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE holidays (
    holiday_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    holiday_date DATE NOT NULL,
    year         INTEGER NOT NULL,
    type         VARCHAR NOT NULL DEFAULT 'National',  -- National|Optional
    location     VARCHAR                               -- per-location applicability (FR-HOL-01)
);
CREATE INDEX ix_holidays_date ON holidays (holiday_date);

CREATE TABLE holiday_optins (
    optin_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     VARCHAR NOT NULL REFERENCES users(emp_id),
    holiday_id BIGINT NOT NULL REFERENCES holidays(holiday_id),
    status     VARCHAR NOT NULL DEFAULT 'Pending',  -- Pending|Approved|Rejected|Cancelled (FR-HOL-03)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_holiday_optins_emp ON holiday_optins (emp_id);

-- ══════════════════════════════════════════════════════════════════════════
--  DOCUMENTS / DEPENDENTS  (FR-DOC, FR-USR-11)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE employee_documents (
    doc_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    doc_type    VARCHAR NOT NULL,
    file_name   VARCHAR,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE documents (
    doc_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    name        VARCHAR NOT NULL,
    category    VARCHAR NOT NULL DEFAULT 'Other',
    file_path   VARCHAR,      -- random object-storage key in v2.0 (CC-14)
    file_size   INTEGER,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_documents_emp ON documents (emp_id);

CREATE TABLE dependents (
    dependent_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    name         VARCHAR NOT NULL,
    relationship VARCHAR NOT NULL,
    date_of_birth DATE
);

-- ══════════════════════════════════════════════════════════════════════════
--  NOTIFICATIONS  (FR-NOT)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id          VARCHAR NOT NULL REFERENCES users(emp_id),
    type            VARCHAR NOT NULL,
    category        VARCHAR DEFAULT 'General',   -- FR-NOT-03 preference category
    message         VARCHAR NOT NULL,
    related_link    VARCHAR,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,  -- mark-read sets TRUE, never deletes (A-26)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_notifications_emp ON notifications (emp_id, is_read);

-- ══════════════════════════════════════════════════════════════════════════
--  ASSETS  (FR-AST)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE assets (
    asset_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id        VARCHAR NOT NULL REFERENCES users(emp_id),
    asset_type    VARCHAR NOT NULL,
    asset_tag     VARCHAR,
    brand         VARCHAR,
    model         VARCHAR,
    serial_number VARCHAR,
    issued_date   DATE NOT NULL,
    return_date   DATE,
    status        VARCHAR NOT NULL DEFAULT 'Issued',   -- Issued|Returned
    notes         VARCHAR
);
CREATE INDEX ix_assets_emp ON assets (emp_id, status);

-- ══════════════════════════════════════════════════════════════════════════
--  RECRUITMENT / ATS  (FR-ATS)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE job_postings (
    job_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR NOT NULL,
    department   VARCHAR,
    location     VARCHAR,
    description  VARCHAR,
    requirements VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Open',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE candidates (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       BIGINT REFERENCES job_postings(job_id),
    name         VARCHAR NOT NULL,
    email        VARCHAR NOT NULL,
    phone        VARCHAR,
    resume_text  VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Applied',  -- Applied|Screened|Interviewed|Offered|Hired|Rejected|Withdrawn
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_candidates_job ON candidates (job_id, status);

CREATE TABLE interviews (
    interview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES candidates(candidate_id),
    scheduled_at TIMESTAMPTZ NOT NULL,
    interviewer  VARCHAR,
    mode         VARCHAR NOT NULL DEFAULT 'In-person',
    feedback     VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Scheduled'
);

CREATE TABLE offer_letters (
    offer_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id    BIGINT NOT NULL REFERENCES candidates(candidate_id),
    offered_salary  NUMERIC(14,2),
    basic_pct       NUMERIC(5,2) NOT NULL,   -- FR-ATS-04: three percentages must sum to 100 (A-20)
    hra_pct         NUMERIC(5,2) NOT NULL,
    allowances_pct  NUMERIC(5,2) NOT NULL,
    offer_date      DATE NOT NULL,
    status          VARCHAR NOT NULL DEFAULT 'Pending',
    accepted_at     TIMESTAMPTZ,
    notes           VARCHAR
);

-- ══════════════════════════════════════════════════════════════════════════
--  ONBOARDING  (FR-ONB)
-- ══════════════════════════════════════════════════════════════════════════
-- Legacy *_tasks tables are retained so no v1.0 data is lost; the v2.0
-- workflow tables below are populated by the corrected flows (Phase 4, §6.5).

CREATE TABLE onboarding_tasks (
    task_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    task_name    VARCHAR NOT NULL,
    assigned_to  VARCHAR NOT NULL,
    status       VARCHAR NOT NULL DEFAULT 'Pending',
    due_date     DATE,
    completed_at TIMESTAMPTZ,
    stage        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE offboarding_tasks (
    task_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    task_name    VARCHAR NOT NULL,
    assigned_to  VARCHAR NOT NULL,
    status       VARCHAR NOT NULL DEFAULT 'Pending',
    due_date     DATE,
    completed_at TIMESTAMPTZ,
    stage        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE exit_interviews (
    interview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    reason       VARCHAR NOT NULL,
    feedback     VARCHAR,
    exit_date    DATE NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    offboard_id  BIGINT
);

CREATE TABLE onboarding_workflow (
    workflow_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    candidate_id BIGINT REFERENCES candidates(candidate_id),
    current_step INTEGER NOT NULL DEFAULT 1,
    step_started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    step1_status VARCHAR NOT NULL DEFAULT 'InProgress',
    step2_status VARCHAR NOT NULL DEFAULT 'Pending',
    step3_status VARCHAR NOT NULL DEFAULT 'Pending',
    step4_status VARCHAR NOT NULL DEFAULT 'Pending',
    step5_status VARCHAR NOT NULL DEFAULT 'Pending',
    completed    BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE onboarding_checklist (
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES onboarding_workflow(workflow_id),
    doc_type    VARCHAR NOT NULL,
    status      VARCHAR NOT NULL DEFAULT 'Pending',  -- Pending|Uploaded|Approved|Rejected
    uploaded_at TIMESTAMPTZ,
    reviewed_by VARCHAR REFERENCES users(emp_id),
    review_note VARCHAR,
    reviewed_at TIMESTAMPTZ
);
ALTER TABLE onboarding_checklist ADD CONSTRAINT uq_checklist_item UNIQUE (workflow_id, doc_type);

-- ══════════════════════════════════════════════════════════════════════════
--  OFFBOARDING  (FR-OFF)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE resignations (
    resignation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id           VARCHAR NOT NULL REFERENCES users(emp_id),
    notice_date      DATE NOT NULL,
    last_working_day DATE NOT NULL,
    reason           VARCHAR,
    initiated_by     VARCHAR NOT NULL,
    status           VARCHAR NOT NULL DEFAULT 'Pending',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    version          INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX ix_resignations_emp ON resignations (emp_id);

CREATE TABLE offboarding_workflow (
    offboard_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resignation_id BIGINT NOT NULL REFERENCES resignations(resignation_id),
    emp_id         VARCHAR NOT NULL REFERENCES users(emp_id),
    stage1_status  VARCHAR NOT NULL DEFAULT 'Pending',
    stage2_status  VARCHAR NOT NULL DEFAULT 'Pending',   -- stages 2 & 3 are independent (parallel, A-16)
    stage3_status  VARCHAR NOT NULL DEFAULT 'Pending',
    stage4_status  VARCHAR NOT NULL DEFAULT 'Pending',
    stage5_status  VARCHAR NOT NULL DEFAULT 'Pending',
    completed      BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_offboarding_workflow_emp ON offboarding_workflow (emp_id, completed);
ALTER TABLE exit_interviews
    ADD CONSTRAINT fk_exit_interviews_offboard
    FOREIGN KEY (offboard_id) REFERENCES offboarding_workflow(offboard_id);

-- FR-OFF-02/03: settlement and stage actions retain a maker-checker trail.
CREATE TABLE offboarding_approvals (
    approval_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offboard_id   BIGINT NOT NULL REFERENCES offboarding_workflow(offboard_id),
    actor_emp_id  VARCHAR NOT NULL REFERENCES users(emp_id),
    action        VARCHAR NOT NULL,       -- Prepare|Approve|Stage1..Stage5
    from_status   VARCHAR NOT NULL,
    to_status     VARCHAR NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_offboarding_approvals_offboard ON offboarding_approvals (offboard_id);

-- FR-OFF-03: Finance full-and-final settlement calculation and maker-checker.
CREATE TABLE offboarding_settlements (
    settlement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offboard_id     BIGINT NOT NULL UNIQUE REFERENCES offboarding_workflow(offboard_id),
    pending_payroll NUMERIC(14,2) NOT NULL DEFAULT 0,
    lop_adjustment  NUMERIC(14,2) NOT NULL DEFAULT 0,
    leave_encashment NUMERIC(14,2) NOT NULL DEFAULT 0,
    deductions      NUMERIC(14,2) NOT NULL DEFAULT 0,
    asset_damage    NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    status          VARCHAR NOT NULL DEFAULT 'Prepared',
    prepared_by     VARCHAR NOT NULL REFERENCES users(emp_id),
    prepared_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by     VARCHAR REFERENCES users(emp_id),
    approved_at     TIMESTAMPTZ
);
CREATE INDEX ix_offboarding_settlements_offboard ON offboarding_settlements (offboard_id);

-- ══════════════════════════════════════════════════════════════════════════
--  PAYROLL  (FR-PAY)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE salary_structures (
    struct_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id         VARCHAR NOT NULL REFERENCES users(emp_id),
    basic          NUMERIC(14,2) NOT NULL DEFAULT 0,
    hra            NUMERIC(14,2) NOT NULL DEFAULT 0,
    allowances     NUMERIC(14,2) NOT NULL DEFAULT 0,
    deductions     NUMERIC(14,2) NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL,
    effective_to   DATE          -- NULL = open-ended; non-overlapping (FR-PAY-02)
);
CREATE INDEX ix_salary_structures_emp ON salary_structures (emp_id);

CREATE TABLE payroll_runs (
    run_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month               INTEGER NOT NULL,
    year                INTEGER NOT NULL,
    processed_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    status              VARCHAR NOT NULL DEFAULT 'Draft',  -- Draft|Submitted|Approved|Finalized|Cancelled
    submitted_by        VARCHAR REFERENCES users(emp_id),
    submitted_at        TIMESTAMPTZ,
    approved_by         VARCHAR REFERENCES users(emp_id),
    approved_at         TIMESTAMPTZ,
    finalized_at        TIMESTAMPTZ,
    adjustment_of_run_id BIGINT REFERENCES payroll_runs(run_id)  -- FR-PAY-06 corrections
);
CREATE INDEX ix_payroll_runs_period ON payroll_runs (year, month);

CREATE TABLE payroll_items (
    item_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            BIGINT NOT NULL REFERENCES payroll_runs(run_id),
    emp_id            VARCHAR NOT NULL REFERENCES users(emp_id),
    gross_salary      NUMERIC(14,2) NOT NULL DEFAULT 0,
    deductions_total  NUMERIC(14,2) NOT NULL DEFAULT 0,
    net_salary        NUMERIC(14,2) NOT NULL DEFAULT 0,
    pf                NUMERIC(14,2) NOT NULL DEFAULT 0,
    esi               NUMERIC(14,2) NOT NULL DEFAULT 0,
    pt                NUMERIC(14,2) NOT NULL DEFAULT 0,
    tds               NUMERIC(14,2) NOT NULL DEFAULT 0,
    lop_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
    reimbursements    NUMERIC(14,2) NOT NULL DEFAULT 0,
    payslip_generated BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_payroll_items_run ON payroll_items (run_id);
CREATE INDEX ix_payroll_items_emp ON payroll_items (emp_id);

-- Maker-checker trail (FR-PAY-06, A-09)
CREATE TABLE payroll_approvals (
    approval_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        BIGINT NOT NULL REFERENCES payroll_runs(run_id),
    actor_emp_id  VARCHAR NOT NULL REFERENCES users(emp_id),
    action        VARCHAR NOT NULL,       -- Submit|Approve|Finalize
    from_status   VARCHAR NOT NULL,
    to_status     VARCHAR NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_payroll_approvals_run ON payroll_approvals (run_id);

-- ══════════════════════════════════════════════════════════════════════════
--  PERFORMANCE  (FR-PERF)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE goals (
    goal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    title       VARCHAR NOT NULL,
    description VARCHAR,
    target_date DATE,
    weight      INTEGER NOT NULL DEFAULT 1,
    rating      INTEGER,          -- rated 1-5 by manager, not self (FR-PERF-01)
    status      VARCHAR NOT NULL DEFAULT 'Active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE performance_reviews (
    review_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id         VARCHAR NOT NULL REFERENCES users(emp_id),
    reviewer_id    VARCHAR NOT NULL REFERENCES users(emp_id),
    review_period  VARCHAR NOT NULL,
    overall_rating REAL,
    comments       VARCHAR,
    status         VARCHAR NOT NULL DEFAULT 'Draft',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    submitted_at   TIMESTAMPTZ
);
CREATE INDEX ix_perf_reviews_emp ON performance_reviews (emp_id);

CREATE TABLE feedback_360 (
    feedback_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    reviewer_id  VARCHAR NOT NULL REFERENCES users(emp_id),
    category     VARCHAR,
    rating       INTEGER,
    comment      VARCHAR,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ══════════════════════════════════════════════════════════════════════════
--  EXPENSES  (FR-EXP)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE expense_categories (
    cat_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR NOT NULL,
    description VARCHAR
);

CREATE TABLE expense_claims (
    claim_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id       VARCHAR NOT NULL REFERENCES users(emp_id),
    cat_id       BIGINT NOT NULL REFERENCES expense_categories(cat_id),
    amount       NUMERIC(14,2) NOT NULL,
    description  VARCHAR,
    receipt_path VARCHAR,
    status       VARCHAR NOT NULL DEFAULT 'Pending',   -- Pending|Approved|Rejected|Paid
    approved_by  VARCHAR REFERENCES users(emp_id),
    paid_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_expense_claims_emp ON expense_claims (emp_id, status);

-- ══════════════════════════════════════════════════════════════════════════
--  TICKETS / HELPDESK  (FR-TKT)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE tickets (
    ticket_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    subject     VARCHAR NOT NULL,
    description VARCHAR,
    queue       VARCHAR DEFAULT 'IT',      -- HR|IT
    category    VARCHAR,
    priority    VARCHAR NOT NULL DEFAULT 'Medium',
    status      VARCHAR NOT NULL DEFAULT 'Open',  -- Open|In Progress|Resolved|Closed|Reopened
    assigned_to VARCHAR REFERENCES users(emp_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX ix_tickets_queue_status ON tickets (queue, status);

CREATE TABLE ticket_comments (
    comment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   BIGINT NOT NULL REFERENCES tickets(ticket_id),
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    comment     VARCHAR NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_ticket_comments_ticket ON ticket_comments (ticket_id);

-- ══════════════════════════════════════════════════════════════════════════
--  AUDIT  (FR-AUD-01) — append-only, never purged by the application
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE audit_log (
    log_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id     VARCHAR REFERENCES users(emp_id),
    actor      VARCHAR,
    action     VARCHAR NOT NULL,
    entity     VARCHAR,
    entity_id  VARCHAR,
    details    VARCHAR,
    "before"   JSONB,
    "after"    JSONB,
    ip_address VARCHAR,
    request_id VARCHAR,        -- CC-13 end-to-end traceability
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_log_emp ON audit_log (emp_id);
CREATE INDEX ix_audit_log_created ON audit_log (created_at);

-- ══════════════════════════════════════════════════════════════════════════
--  RBAC  (§2.2 / Appendix B)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE user_permissions (
    perm_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id      VARCHAR NOT NULL REFERENCES users(emp_id),
    module      VARCHAR NOT NULL,          -- payroll_approve|shift_admin|policy_admin|pii_reveal|...
    allow       BOOLEAN NOT NULL DEFAULT TRUE,   -- explicit deny beats allow
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ
);
ALTER TABLE user_permissions ADD CONSTRAINT uq_user_permission UNIQUE (emp_id, module);
CREATE INDEX ix_user_permissions_emp ON user_permissions (emp_id);

-- ══════════════════════════════════════════════════════════════════════════
--  INFRASTRUCTURE  (CC-09 outbox, CC-07 idempotency)
-- ══════════════════════════════════════════════════════════════════════════

CREATE TABLE outbox_events (
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR NOT NULL,
    aggregate       VARCHAR,
    aggregate_id    VARCHAR,
    payload         JSONB,
    status          VARCHAR NOT NULL DEFAULT 'pending',  -- pending|delivered|failed|dead_letter
    attempts        INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at    TIMESTAMPTZ
);
CREATE INDEX ix_outbox_status ON outbox_events (status, next_attempt_at);

CREATE TABLE idempotency_keys (
    key             VARCHAR PRIMARY KEY,
    route           VARCHAR NOT NULL,
    request_hash    VARCHAR NOT NULL,
    response_status INTEGER NOT NULL,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL
);

-- ============================================================================
--  PART B — INVARIANTS (activate ONLY after the Phase-1 ETL data-cleanup pass)
-- ============================================================================

-- CC-05 / FR-ATT-02: exactly one Active break per employee
CREATE UNIQUE INDEX uq_one_active_break
    ON breaks (emp_id) WHERE status = 'Active';

-- FR-USR-02: email uniqueness, case-insensitive
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));

-- CC-05 / FR-ATT-17: shift rows for one employee never overlap effective ranges
ALTER TABLE shift_assignments ADD CONSTRAINT no_overlapping_shift
    EXCLUDE USING gist (
        emp_id WITH =,
        daterange(effective_from, effective_to, '[)') WITH &&
    );

-- CC-05 / FR-ATT-05: one Pending Lunch approval per employee per shift date
CREATE UNIQUE INDEX uq_pending_lunch_approval
    ON break_approvals (emp_id, break_type, break_date) WHERE status = 'Pending';

-- CC-05 / FR-REG-02: one Pending regularization per employee per date
CREATE UNIQUE INDEX uq_pending_regularization
    ON regularization_requests (emp_id, request_date) WHERE status = 'Pending';

-- CC-05 / FR-LEA-02: no overlapping Pending/Approved leave
ALTER TABLE leave_requests ADD CONSTRAINT no_overlapping_leave
    EXCLUDE USING gist (
        emp_id WITH =,
        daterange(start_date, end_date, '[]') WITH &&
    ) WHERE (status IN ('Pending', 'Approved'));

-- FR-LEA-06: one leave_balance row per employee/type/year
ALTER TABLE leave_balance ADD CONSTRAINT uq_balance UNIQUE (emp_id, leave_type, year);

-- FR-PAY-05: one payroll run per month/year unless cancelled
CREATE UNIQUE INDEX uq_payroll_period
    ON payroll_runs (month, year) WHERE status <> 'Cancelled';

-- FR-PAY-02: non-overlapping salary structures per employee
ALTER TABLE salary_structures ADD CONSTRAINT no_overlapping_structure
    EXCLUDE USING gist (
        emp_id WITH =,
        daterange(effective_from, effective_to, '[)') WITH &&
    );

-- FR-ONB-03: one active onboarding workflow per employee
CREATE UNIQUE INDEX uq_active_onboarding
    ON onboarding_workflow (emp_id) WHERE completed = FALSE;

-- FR-OFF-01: one active resignation per employee
CREATE UNIQUE INDEX uq_active_resignation
    ON resignations (emp_id) WHERE status NOT IN ('Cancelled', 'Revoked');

-- FR-ATS-04: offer split percentages sum to 100 (A-20)
ALTER TABLE offer_letters ADD CONSTRAINT split_sums_100
    CHECK (basic_pct IS NOT NULL AND hra_pct IS NOT NULL AND allowances_pct IS NOT NULL
           AND basic_pct + hra_pct + allowances_pct = 100);
CREATE UNIQUE INDEX uq_active_offer_candidate
    ON offer_letters (candidate_id) WHERE status IN ('Pending', 'Accepted');

-- FR-HOL-03: one opt-in per employee/holiday
ALTER TABLE holiday_optins ADD CONSTRAINT uq_optin UNIQUE (emp_id, holiday_id);

COMMIT;